/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayoutHeader: typeof import('src/components/AppLayoutHeader')['AppLayoutHeader']
    Ax: typeof import('./src/components/Test/Amir/Sama/Ax.vue')['default']
    Content: typeof import('./src/components/App/Layout/Content.vue')['default']
    Drawer: typeof import('./src/components/App/Setting/Drawer.vue')['default']
    Header: typeof import('./src/components/App/Layout/Header.vue')['default']
    RadioGroupColor: typeof import('./src/components/RadioGroupColor.vue')['default']
    RadioGroupImage: typeof import('./src/components/RadioGroupImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('./src/components/App/Layout/Slider.vue')['default']
  }
}
